import image1 from '../assets/music/uza.jpg'
import image2 from '../assets/music/yuza.jpg'
import image3 from '../assets/music/hands.png'
import image4 from '../assets/music/zova.jpg'
import image5 from '../assets/music/hands.png'
import image6 from '../assets/music/image6.jpg'
import image7 from '../assets/music/image7.jpg'
import image8 from '../assets/music/image8.jpg'
import image9 from '../assets/music/image9.jpg'
import image10 from '../assets/music/image10.jpg'
import image11 from '../assets/music/image11.jpg'
import image12 from '../assets/music/image12.jpg'
import image13 from '../assets/music/image13.jpg'
import image14 from '../assets/music/image14.jpg'
import image15 from '../assets/music/gazo.jpg'
import image16 from '../assets/music/image16.jpg'
import image17 from '../assets/music/image17.jpg'
import image18 from '../assets/music/image18.jpg'
import image19 from '../assets/music/eric.jpg'
import image20 from '../assets/music/clay-banks.jpg'


export const reviewData = [
    {
      id: 1,
      artistName: "DJ Fela",
      artistBio: "A rising Amapiano star known for her infectious grooves and energetic live shows.",
      songName: "Umshini Wami",
      songReview: "This Amapiano banger is guaranteed to get you moving!",
      rating: 4.8,
      genre:"Amapiano",
      image: image1,
      streamingStats: {
        platformEngagement: { Spotify: 75000, AppleMusic: 35000, YouTubeMusic: 125000 },
        artistStreamingStats: { monthlyListeners: 600000, totalStreams: 30000000 },
        songStreamingStats: { streams: 400000, downloads: 20000 },
      },
      revenuePotential: { estimatedRevenue: 85000, suggestedPromoStrategy: "Collaborate with popular Amapiano DJs and influencers. Utilize social media and targeted ads to reach Amapiano fans.", estimatedBudget: 45000 },
      nftData: { suggestedNfts: 500, nftPrice: 0.075, zarPrice: 37.50 },
      songSnippet: "https://example.com/umshini-wami-snippet.mp3",
      shareMenu: [
        { icon: "facebook", label: "Share on Facebook" },
        { icon: "twitter", label: "Share on Twitter" },
        { icon: "instagram", label: "Share on Instagram" },
      ],
    },
    {
      id: 2,
      artistName: "Black Coffee Jr.",
      artistBio: "A young Gqom producer pushing the boundaries of the genre with dark basslines and innovative sounds.",
      songName: "Into the Lab",
      songReview: "This Gqom track is intense and experimental.",
      rating: 4.7,
      genre:"Gqom",
      image: image2,
      streamingStats: {
        platformEngagement: { Spotify: 40000, AppleMusic: 20000, YouTubeMusic: 60000 },
        artistStreamingStats: { monthlyListeners: 250000, totalStreams: 12500000 },
        songStreamingStats: { streams: 200000, downloads: 10000 },
      },
      revenuePotential: { estimatedRevenue: 55000, suggestedPromoStrategy: "Target online Gqom communities and showcase the limited-edition artwork NFT.", estimatedBudget: 30000 },
      nftData: { suggestedNfts: 100, nftPrice: 0.25, zarPrice: 125.00 },
      songSnippet: "https://example.com/into-the-lab-snippet.mp3",
      shareMenu: [
        { icon: "facebook", label: "Share on Facebook" },
        { icon: "twitter", label: "Share on Twitter" },
        { icon: "instagram", label: "Share on Instagram" },
      ],
     
    },
    {
      id: 3,
      artistName: "Kabza De Small",
      artistBio: "A renowned South African DJ and producer known for his unique blend of Amapiano, Afro-Pop, and electronic music.",
      songName: "eMcimbini",
      songReview: "This Amapiano track showcases Kabza De Small's impressive production skills and genre-bending style, making it a standout hit.",
      rating: 4.9,
      genre: "Amapiano",
      image: image3,
      streamingStats: {
        platformEngagement: { Spotify: 120000, AppleMusic: 60000, YouTubeMusic: 250000 },
        artistStreamingStats: { monthlyListeners: 600000, totalStreams: 30000000 },
        songStreamingStats: { streams: 450000, downloads: 22500 },
      },
      revenuePotential: { estimatedRevenue: 120000, suggestedPromoStrategy: "Target fans of Amapiano and Afro-Pop music, and collaborate with influencers and bloggers in the genre.", estimatedBudget: 60000 },
      nftData: { suggestedNfts: 350, nftPrice: 0.10, zarPrice: 50.00 },
      songSnippet: "https://example.com/emcimbini-snippet.mp3",
      shareMenu: [
        { icon: "facebook", label: "Share on Facebook" },
        { icon: "twitter", label: "Share on Twitter" },
        { icon: "instagram", label: "Share on Instagram" },
      ],
    },
    {
      id: 4,
      artistName: "Mzansi Beats",
      artistBio: "A South African house music collective known for their upbeat rhythms and dancefloor anthems.",
      songName: "Township Groove",
      songReview: "This house track is pure energy! It's guaranteed to get any party started.",
      rating: 4.5,
      genre:"House",
      image:image4,
      streamingStats: {
        platformEngagement: { Spotify: 50000, AppleMusic: 25000, YouTubeMusic: 75000 },
        artistStreamingStats: { monthlyListeners: 350000, totalStreams: 17500000 },
        songStreamingStats: { streams: 250000, downloads: 12500 },
      },
      revenuePotential: { estimatedRevenue: 60000, suggestedPromoStrategy: "Promote the exclusive online listening party to attract house music fans and NFT collectors.", estimatedBudget: 35000 },
      nftData: { suggestedNfts: 300, nftPrice: 0.10, zarPrice: 50.00 },
      songSnippet: "https://example.com/township-groove-snippet.mp3",
      shareMenu: [
        { icon: "facebook", label: "Share on Facebook" },
        { icon: "twitter", label: "Share on Twitter" },
        { icon: "instagram", label: "Share on Instagram" },
      ],
    },
    {
      id: 5,
      artistName: "Moonchild Sanelly",
      artistBio: "A genre-bending singer-songwriter known for her energetic live performances and unique blend of traditional and modern styles.",
      songName: "Makhe",
      songReview: "This Afro-Pop track is an infectious dancefloor filler.",
      rating: 4.9,
      genre: "Afro-Pop",
      image: image15,
      streamingStats: {
        platformEngagement: { Spotify: 100000, AppleMusic: 50000, YouTubeMusic: 200000 },
        artistStreamingStats: { monthlyListeners: 500000, totalStreams: 25000000 },
        songStreamingStats: { streams: 500000, downloads: 25000 },
      },
      revenuePotential: { estimatedRevenue: 100000, suggestedPromoStrategy: "Collaborate with popular Afro-Pop artists and influencers. Utilize social media and targeted ads to reach Afro-Pop fans.", estimatedBudget: 50000 },
      nftData: { suggestedNfts: 1000, nftPrice: 0.05, zarPrice: 25.00 },
      songSnippet: "https://example.com/makhe-snippet.mp3",
      shareMenu: [
        { icon: "facebook", label: "Share on Facebook" },
        { icon: "twitter", label: "Share on Twitter" },
        { icon: "instagram", label: "Share on Instagram" },
      ],
    },
    {
      id: 6,
      artistName: "Sjava",
      artistBio: "A critically acclaimed rapper and poet known for his thought-provoking lyrics and unique blend of traditional and modern styles.",
      songName: "Ugogo",
      songReview: "This Hip-Hop track is a powerful exploration of identity, culture, and social justice.",
      rating: 4.8,
      genre: "Hip-Hop/Rap",
      image: image6,
      streamingStats: {
        platformEngagement: { Spotify: 80000, AppleMusic: 40000, YouTubeMusic: 150000 },
        artistStreamingStats: { monthlyListeners: 400000, totalStreams: 20000000 },
        songStreamingStats: { streams: 300000, downloads: 15000 },
      },
      revenuePotential: { estimatedRevenue: 80000, suggestedPromoStrategy: "Target fans of conscious Hip-Hop and collaborate with influencers and bloggers in the genre.", estimatedBudget: 40000 },
      nftData: { suggestedNfts: 500, nftPrice: 0.10, zarPrice: 50.00 },
      songSnippet: "https://example.com/ugogo-snippet.mp3",
      shareMenu: [
        { icon: "facebook", label: "Share on Facebook" },
        { icon: "twitter", label: "Share on Twitter" },
        { icon: "instagram", label: "Share on Instagram" },
      ],
    },
    {
      id: 7,
      artistName: "Desmond & The Tutus",
      artistBio: "A quirky indie-rock band known for their catchy hooks, witty lyrics, and energetic live performances.",
      songName: "Pretoria Girls",
      songReview: "This indie-rock track is a fun, upbeat ode to the beauty of Pretoria's women.",
      rating: 4.7,
      genre: "Indie-Rock",
      image: image7,
      streamingStats: {
        platformEngagement: { Spotify: 60000, AppleMusic: 30000, YouTubeMusic: 100000 },
        artistStreamingStats: { monthlyListeners: 300000, totalStreams: 15000000 },
        songStreamingStats: { streams: 200000, downloads: 10000 },
      },
      revenuePotential: { estimatedRevenue: 60000, suggestedPromoStrategy: "Target fans of indie-rock and collaborate with influencers and bloggers in the genre.", estimatedBudget: 30000 },
      nftData: { suggestedNfts: 200, nftPrice: 0.20, zarPrice: 100.00 },
      songSnippet: "https://example.com/pretoria-girls-snippet.mp3",
      shareMenu: [
        { icon: "facebook", label: "Share on Facebook" },
        { icon: "twitter", label: "Share on Twitter" },
        { icon: "instagram", label: "Share on Instagram" },
      ],
    },
    {
      id: 8,
      artistName: "Samthing Soweto",
      artistBio: "A soulful singer-songwriter known for his powerful vocals and genre-bending style, which blends elements of Afro-Pop, R&B, and traditional South African music.",
      songName: "Akulaleki",
      songReview: "This soulful Afro-Pop track showcases Samthing's impressive vocal range.",
      rating: 4.9,
      genre: "Afro-Pop",
      image: image8,
      streamingStats: {
        platformEngagement: { Spotify: 120000, AppleMusic: 60000, YouTubeMusic: 250000 },
        artistStreamingStats: { monthlyListeners: 600000, totalStreams: 30000000 },
        songStreamingStats: { streams: 400000, downloads: 20000 },
      },
      revenuePotential: { estimatedRevenue: 120000, suggestedPromoStrategy: "Target fans of Afro-Pop and R&B, and collaborate with influencers and bloggers in the genre.", estimatedBudget: 60000 },
      nftData: { suggestedNfts: 300, nftPrice: 0.15, zarPrice: 75.00 },
      songSnippet: "https://example.com/akulaleki-snippet.mp3",
      shareMenu: [
        { icon: "facebook", label: "Share on Facebook" },
        { icon: "twitter", label: "Share on Twitter" },
        { icon: "instagram", label: "Share on Instagram" },
      ],
    },
    {
      id: 9,
      artistName: "Sun-El Musician",
      artistBio: "A talented DJ and producer known for his soulful and uplifting electronic music, often incorporating elements of Afro-Pop and traditional South African sounds.",
      songName: "To the Moon",
      songReview: "This feel-good electronic track features Sun-El's signature blend of Afro-Pop and deep house.",
      rating: 4.8,
      genre: "Electronic/Afro-Pop",
      image: image9,
      streamingStats: {
        platformEngagement: { Spotify: 90000, AppleMusic: 45000, YouTubeMusic: 180000 },
        artistStreamingStats: { monthlyListeners: 450000, totalStreams: 22500000 },
        songStreamingStats: { streams: 350000, downloads: 17500 },
      },
      revenuePotential: { estimatedRevenue: 90000, suggestedPromoStrategy: "Target fans of electronic and Afro-Pop music, and collaborate with influencers and bloggers in the genre.", estimatedBudget: 45000 },
      nftData: { suggestedNfts: 250, nftPrice: 0.20, zarPrice: 100.00 },
      songSnippet: "https://example.com/to-the-moon-snippet.mp3",
      shareMenu: [
        { icon: "facebook", label: "Share on Facebook" },
        { icon: "twitter", label: "Share on Twitter" },
        { icon: "instagram", label: "Share on Instagram" },
      ],
    },
    {
      id: 10,
      artistName: "Mthunzi",
      artistBio: "A rising star in the South African music scene, known for his soulful voice and genre-bending style, which blends elements of R&B, Afro-Pop, and traditional South African music.",
      songName: "Uyathandwa",
      songReview: "This soulful R&B track showcases Mthunzi's impressive vocal range.",
      rating: 4.9,
      genre: "R&B/Afro-Pop",
      image: image10,
      streamingStats: {
        platformEngagement: { Spotify: 100000, AppleMusic: 50000, YouTubeMusic: 200000 },
        artistStreamingStats: { monthlyListeners: 500000, totalStreams: 25000000 },
        songStreamingStats: { streams: 400000, downloads: 20000 },
      },
      revenuePotential: { estimatedRevenue: 100000, suggestedPromoStrategy: "Target fans of R&B and Afro-Pop music, and collaborate with influencers and bloggers in the genre.", estimatedBudget: 50000 },
      nftData: { suggestedNfts: 200, nftPrice: 0.25, zarPrice: 125.00 },
      songSnippet: "https://example.com/uyathandwa-snippet.mp3",
      shareMenu: [
        { icon: "facebook", label: "Share on Facebook" },
        { icon: "twitter", label: "Share on Twitter" },
        { icon: "instagram", label: "Share on Instagram" },
      ],
    },
    {
      id: 11,
      artistName: "Zakwe",
      artistBio: "A renowned South African rapper known for his lyrical prowess and unique blend of traditional and modern styles.",
      songName: "Mabena",
      songReview: "This Hip-Hop track showcases Zakwe's impressive storytelling ability.",
      rating: 4.8,
      genre: "Hip-Hop/Rap",
      image: image11,
      streamingStats: {
        platformEngagement: { Spotify: 80000, AppleMusic: 40000, YouTubeMusic: 150000 },
        artistStreamingStats: { monthlyListeners: 400000, totalStreams: 20000000 },
        songStreamingStats: { streams: 300000, downloads: 15000 },
      },
      revenuePotential: { estimatedRevenue: 80000, suggestedPromoStrategy: "Target fans of Hip-Hop and collaborate with influencers and bloggers in the genre.", estimatedBudget: 40000 },
      nftData: { suggestedNfts: 300, nftPrice: 0.15, zarPrice: 75.00 },
      songSnippet: "https://example.com/mabena-snippet.mp3",
      shareMenu: [
        { icon: "facebook", label: "Share on Facebook" },
        { icon: "twitter", label: "Share on Twitter" },
        { icon: "instagram", label: "Share on Instagram" },
      ],
    },
    {
      id: 12,
      artistName: "Nasty C",
      artistBio: "A critically acclaimed South African rapper known for his thought-provoking lyrics and genre-bending style, which blends elements of Hip-Hop, R&B, and traditional South African music.",
      songName: "Juice Back",
      songReview: "This Hip-Hop track showcases Nasty C's impressive lyrical ability.",
      rating: 4.9,
      genre: "Hip-Hop/Rap",
      image: image12,
      streamingStats: {
        platformEngagement: { Spotify: 120000, AppleMusic: 60000, YouTubeMusic: 250000 },
        artistStreamingStats: { monthlyListeners: 600000, totalStreams: 30000000 },
        songStreamingStats: { streams: 400000, downloads: 20000 },
      },
      revenuePotential: { estimatedRevenue: 120000, suggestedPromoStrategy: "Target fans of Hip-Hop and collaborate with influencers and bloggers in the genre.", estimatedBudget: 60000 },
      nftData: { suggestedNfts: 400, nftPrice: 0.10, zarPrice: 50.00 },
      songSnippet: "https://example.com/juice-back-snippet.mp3",
      shareMenu: [
        { icon: "facebook", label: "Share on Facebook" },
        { icon: "twitter", label: "Share on Twitter" },
        { icon: "instagram", label: "Share on Instagram" },
      ],
    },
    {
      id: 13,
      artistName: "Lady Zamar",
      artistBio: "A talented South African singer-songwriter known for her soulful voice and genre-bending style, which blends elements of Afro-Pop, R&B, and electronic music.",
      songName: "Collide",
      songReview: "This Afro-Pop track showcases Lady Zamar's impressive vocal range.",
      rating: 4.8,
      genre: "Afro-Pop",
      image: image13,
      streamingStats: {
        platformEngagement: { Spotify: 90000, AppleMusic: 45000, YouTubeMusic: 180000 },
        artistStreamingStats: { monthlyListeners: 450000, totalStreams: 22500000 },
        songStreamingStats: { streams: 350000, downloads: 17500 },
      },
      revenuePotential: { estimatedRevenue: 90000, suggestedPromoStrategy: "Target fans of Afro-Pop and R&B music, and collaborate with influencers and bloggers in the genre.", estimatedBudget: 45000 },
      nftData: { suggestedNfts: 250, nftPrice: 0.20, zarPrice: 100.00 },
      songSnippet: "https://example.com/collide-snippet.mp3",
      shareMenu: [
        { icon: "facebook", label: "Share on Facebook" },
        { icon: "twitter", label: "Share on Twitter" },
        { icon: "instagram", label: "Share on Instagram" },
      ],
    },
    {
      id: 14,
      artistName: "Black Motion",
      artistBio: "A critically acclaimed South African electronic music duo known for their unique blend of traditional and modern styles, which incorporates elements of Afro-Pop, House, and Kwaito music.",
      songName: "The Journey",
      songReview: "This electronic track showcases Black Motion's impressive production skills.",
      rating: 4.9,
      genre: "Electronic/Afro-Pop",
      image: image14,
      streamingStats: {
        platformEngagement: { Spotify: 100000, AppleMusic: 50000, YouTubeMusic: 200000 },
        artistStreamingStats: { monthlyListeners: 500000, totalStreams: 25000000 },
        songStreamingStats: { streams: 400000, downloads: 20000 },
      },
      revenuePotential: { estimatedRevenue: 100000, suggestedPromoStrategy: "Target fans of electronic and Afro-Pop music, and collaborate with influencers and bloggers in the genre.", estimatedBudget: 50000 },
      nftData: { suggestedNfts: 300, nftPrice: 0.15, zarPrice: 75.00 },
      songSnippet: "https://example.com/the-journey-snippet.mp3",
      shareMenu: [
        { icon: "facebook", label: "Share on Facebook" },
        { icon: "twitter", label: "Share on Twitter" },
        { icon: "instagram", label: "Share on Instagram" },
      ],
    },{
      id: 15,
      artistName: "Prince Kaybee",
      artistBio: "A renowned South African DJ and producer known for his unique blend of House, Afro-Pop, and traditional South African music.",
      songName: "Gugulethu",
      songReview: "This House track showcases Prince Kaybee's impressive production skills",
      rating: 4.8,
      genre: "House",
      image: image15,
      streamingStats: {
        platformEngagement: { Spotify: 80000, AppleMusic: 40000, YouTubeMusic: 150000 },
        artistStreamingStats: { monthlyListeners: 400000, totalStreams: 20000000 },
        songStreamingStats: { streams: 300000, downloads: 15000 },
      },
      revenuePotential: { estimatedRevenue: 80000, suggestedPromoStrategy: "Target fans of House music and collaborate with influencers and bloggers in the genre.", estimatedBudget: 40000 },
      nftData: { suggestedNfts: 250, nftPrice: 0.20, zarPrice: 100.00 },
      songSnippet: "https://example.com/gugulethu-snippet.mp3",
      shareMenu: [
        { icon: "facebook", label: "Share on Facebook" },
        { icon: "twitter", label: "Share on Twitter" },
        { icon: "instagram", label: "Share on Instagram" },
      ],
    }, {
      id: 16,
      artistName: "Sho Madjozi",
      artistBio: "A talented South African rapper and singer-songwriter known for her unique blend of Hip-Hop, Afro-Pop, and traditional Tsonga music.",
      songName: "John Cena",
      songReview: "This Hip-Hop track showcases Sho Madjozi's impressive lyrical ability.",
      rating: 4.9,
      genre: "Hip-Hop/Afro-Pop",
      image: image16,
      streamingStats: {
        platformEngagement: { Spotify: 100000, AppleMusic: 50000, YouTubeMusic: 200000 },
        artistStreamingStats: { monthlyListeners: 500000, totalStreams: 25000000 },
        songStreamingStats: { streams: 400000, downloads: 20000 },
      },
      revenuePotential: { estimatedRevenue: 100000, suggestedPromoStrategy: "Target fans of Hip-Hop and Afro-Pop music, and collaborate with influencers and bloggers in the genre.", estimatedBudget: 50000 },
      nftData: { suggestedNfts: 300, nftPrice: 0.15, zarPrice: 75.00 },
      songSnippet: "https://example.com/john-cena-snippet.mp3",
      shareMenu: [
        { icon: "facebook", label: "Share on Facebook" },
        { icon: "twitter", label: "Share on Twitter" },
        { icon: "instagram", label: "Share on Instagram" },
      ],
    },
    {
      id: 17,
      artistName: "Mafikizolo",
      artistBio: "A legendary South African Afro-Pop duo known for their catchy hooks, infectious rhythms, and iconic hits that have defined the sound of South African music.",
      songName: "Kwela Kwela",
      songReview: "This Afro-Pop track showcases Mafikizolo's signature sound and style.",
      rating: 4.8,
      genre: "Afro-Pop",
      image: image17,
      streamingStats: {
        platformEngagement: { Spotify: 70000, AppleMusic: 35000, YouTubeMusic: 140000 },
        artistStreamingStats: { monthlyListeners: 350000, totalStreams: 17500000 },
        songStreamingStats: { streams: 250000, downloads: 12500 },
      },
      revenuePotential: { estimatedRevenue: 70000, suggestedPromoStrategy: "Target fans of Afro-Pop music and collaborate with influencers and bloggers in the genre.", estimatedBudget: 35000 },
      nftData: { suggestedNfts: 200, nftPrice: 0.25, zarPrice: 125.00 },
      songSnippet: "https://example.com/kwela-kwela-snippet.mp3",
      shareMenu: [
        { icon: "facebook", label: "Share on Facebook" },
        { icon: "twitter", label: "Share on Twitter" },
        { icon: "instagram", label: "Share on Instagram" },
      ],
    },
    {
      id: 18,
      artistName: "Simmy",
      artistBio: "A talented South African singer-songwriter known for her soulful voice and genre-bending style, which blends elements of Afro-Pop, R&B, and electronic music.",
      songName: "Ngiyesaba",
      songReview: "This Afro-Pop track showcases Simmy's impressive vocal range.",
      rating: 4.9,
      genre: "Afro-Pop",
      image: image18,
      streamingStats: {
        platformEngagement: { Spotify: 90000, AppleMusic: 45000, YouTubeMusic: 180000 },
        artistStreamingStats: { monthlyListeners: 450000, totalStreams: 22500000 },
        songStreamingStats: { streams: 350000, downloads: 17500 },
      },
      revenuePotential: { estimatedRevenue: 90000, suggestedPromoStrategy: "Target fans of Afro-Pop and R&B music, and collaborate with influencers and bloggers in the genre.", estimatedBudget: 45000 },
      nftData: { suggestedNfts: 250, nftPrice: 0.20, zarPrice: 100.00 },
      songSnippet: "https://example.com/ngiyesaba-snippet.mp3",
      shareMenu: [
        { icon: "facebook", label: "Share on Facebook" },
        { icon: "twitter", label: "Share on Twitter" },
        { icon: "instagram", label: "Share on Instagram" },
      ],
    },
    {
      id: 19,
      artistName: "Ami Faku",
      artistBio: "A talented South African singer-songwriter known for her soulful voice and genre-bending style, which blends elements of Afro-Pop, R&B, and traditional South African music.",
      songName: "Ubuhle Bakho",
      songReview: "This Afro-Pop track showcases Ami Faku's impressive vocal range.",
      rating: 4.8,
      genre: "Afro-Pop",
      image: image19,
      streamingStats: {
        platformEngagement: { Spotify: 80000, AppleMusic: 40000, YouTubeMusic: 150000 },
        artistStreamingStats: { monthlyListeners: 400000, totalStreams: 20000000 },
        songStreamingStats: { streams: 300000, downloads: 15000 },
      },
      revenuePotential: { estimatedRevenue: 80000, suggestedPromoStrategy: "Target fans of Afro-Pop and R&B music, and collaborate with influencers and bloggers in the genre.", estimatedBudget: 40000 },
      nftData: { suggestedNfts: 200, nftPrice: 0.25, zarPrice: 125.00 },
      songSnippet: "https://example.com/ubuhle-bakho-snippet.mp3",
      shareMenu: [
        { icon: "facebook", label: "Share on Facebook" },
        { icon: "twitter", label: "Share on Twitter" },
        { icon: "instagram", label: "Share on Instagram" },
      ],
    },
    {
      id: 20,
      artistName: "De Mthuda",
      artistBio: "A talented South African DJ and producer known for his unique blend of Amapiano, Afro-Pop, and electronic music.",
      songName: "Shesha",
      songReview: "This Amapiano track showcases De Mthuda's impressive production skills",
      rating: 4.9,
      genre: "Amapiano",
      image: image20,
      streamingStats: {
        platformEngagement: { Spotify: 100000, AppleMusic: 50000, YouTubeMusic: 200000 },
        artistStreamingStats: { monthlyListeners: 500000, totalStreams: 25000000 },
        songStreamingStats: { streams: 400000, downloads: 20000 },
      },
      revenuePotential: { estimatedRevenue: 100000, suggestedPromoStrategy: "Target fans of Amapiano and Afro-Pop music, and collaborate with influencers and bloggers in the genre.", estimatedBudget: 50000 },
      nftData: { suggestedNfts: 300, nftPrice: 0.15, zarPrice: 75.00 },
      songSnippet: "https://example.com/shesha-snippet.mp3",
      shareMenu: [
        { icon: "facebook", label: "Share on Facebook" },
        { icon: "twitter", label: "Share on Twitter" },
        { icon: "instagram", label: "Share on Instagram" },
      ],
    }

  ];
  

  