// Enum to define user roles

enum UserRole {
    ORDINARY_USER = "ORDINARY_USER",
    ASPIRING_REVIEWER = "ASPIRING_REVIEWER",
    CERTIFIED_REVIEWER = "CERTIFIED_REVIEWER",
    MEDIA_AFFILIATE = "MEDIA_AFFILIATE ",
    TEAM_INSIDER = "TEAM_INSIDER",
    ELITE_WRITER = "ELITE_WRITER",
  }